{% set name = "trame-plotly" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-plotly-{{ version }}.tar.gz
  sha256: 71a9d17047bda071550dc2020b7014be35fd7e69c13f0b30868553b4f94bfab4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - trame-client

test:
  imports:
    - trame
    - trame.modules
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame-plotly/
  summary: Plotly figure widget for trame
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
